version: '3.7'
services:
  mongodb_container:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: mongo-replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: ahroyal
    ports:
      - '37017:27017'
      - '27017:27017'
    volumes:
      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d